DeForce/LalkaChat

conf/df.cfg, modules/messaging/df.py
=> LC-51 Fix df module

http/css/czt.css, http/js/socket.js, modules/chat_system.py, modules/goodgame.py, modules/messaging/levels.py, modules/sc2tv.py, modules/twitch.py
=> LC-11 System Messages changes

conf/config.cfg, conf/webchat.cfg, gui.py, main.py, modules/messaging/webchat.py
=> LC-40 Implement box for language select

conf/blacklist.cfg, conf/c2b.cfg, conf/logger.cfg, conf/messaging.cfg, messaging.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-63 Load modules according to priority

modules/chats/sc2tv.py
=> LC-69 Fix premium smiles for sc2tv

gui.py, main.py, modules/helpers/parser.py
=> LC-20 Remember window size

gui.py
=> LC-91 Strip spaces from inputs if they appear

gui.py, main.py
=> LC-81 Close chat after closing gui

main.py, modules/chats/goodgame.py, modules/chats/sc2tv.py, modules/chats/twitch.py
=> LC-61 Show system messages in http

gui.py, main.py, messaging.py, modules/chats/goodgame.py, modules/chats/sc2tv.py, modules/chats/twitch.py, modules/helpers/parser.py, modules/messaging/df.py, modules/messaging/mentions.py, translations/en/levels.key
=> LC-101 TextCtrl's doesn't align nicely and small fixes

gui.py, main.py, messaging.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-62 Warn to restart chat after non-dynamic changes

gui.py, translations/en/goodgame.key, translations/en/main.key, translations/en/sc2tv.key, translations/en/twitch.key, translations/ru/goodgame.key, translations/ru/main.key, translations/ru/sc2tv.key, translations/ru/twitch.key
=> LC-106 Switch multiple choice to CheckListBox

modules/messaging/webchat.py
=> LC-102 Check for port usage for webchat

modules/messaging/levels.py
=> LC-92 Add threshold/diminishing returns to levels

gui.py, main.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py
=> LC-66 Setup reconnecting after disconnect in chats

gui.py, main.py, translations/en/main.key, translations/ru/main.key
=> LC-71 Set default chat language to OS language

gui.py, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, translations/en/main.key, translations/ru/main.key
=> LC-68 Changed to tree style configuration

gui.py, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/modules.py, modules/messaging/levels.py, modules/messaging/webchat.py
=> LC-126 Rewrite messaging module initialization

http/czt/js/socket.js, main.py
Release 0.3.1 hotfix - remove of removing old messages
=> Release 0.3.1 hotfix - remove of removing old messages

http/czt/js/socket.js, modules/chat/goodgame.py
=> LC-23 Add ban/unban/warn messages for goodgame.ru

http/czt/js/socket.js, modules/chat/twitch.py
=> LC-137 Delete messages from Twitch

gui.py
=> LC-143 Hide category panel, reuse if chosen

gui.py, http/czt/js/socket.js, main.py, modules/chat/twitch.py, modules/helper/parser.py, modules/helper/system.py, modules/messaging/webchat.py
=> LC-103 Apply button should be grayed out before any changes

gui.py, translations/en/main.key, translations/ru/main.key
=> LC-147 rewrite setting window button logic

http/czt/js/socket.js, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/system.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-146 split remove to different calls

http/czt/css/style.css, http/czt/index.html
=> LC-160 Fix css in standard style

http/czt/js/app.js, modules/helper/modules.py, modules/messaging/webchat.py
=> LC-54 Rest start and ability to timer out messages

docker/Dockerfiles/alpine-wxpython/Dockerfile
=> Third time's the charm

gui.py, http/czt/css/style.css, http/czt/js/app.js, http/czt/settings.json, http/czt/settings_gui.json, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/module.py, modules/helper/parser.py, modules/helper/system.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-128 Custom Style settings

http/czt/index.html, modules/chat/twitch.py
=> LC-192 Fix deleting twitch usernames

http/czt/css/style.css, http/czt/index.html, modules/chat/twitch.py
=> LC-194 Rewrite Twitch message logic

http/czt/index.html, http/czt/js/app.js, http/czt/settings.json, modules/chat/goodgame.py, modules/chat/twitch.py, modules/helper/system.py, modules/messaging/levels.py, modules/messaging/webchat.py
=> LC-138 Allow to change text in removed message

.travis.yml, Dockerfile, Dockerfile_test, README.md, docker/Dockerfiles/alpine-wxpython/Dockerfile, docker/Dockerfiles/lalkachat-build-deps/Dockerfile, docker/run, http/czt/js/app.js, http/czt_timed/js/socket.js, travis/main.sh, travis/test-conf/blacklist.cfg, travis/test-conf/c2b.cfg, travis/test-conf/chat_modules.cfg, travis/test-conf/config.cfg, travis/test-conf/df.cfg, travis/test-conf/goodgame.cfg, travis/test-conf/levels.cfg, travis/test-conf/logger.cfg, travis/test-conf/mentions.cfg, travis/test-conf/messaging_modules.cfg, travis/test-conf/sc2tv.cfg, travis/test-conf/twitch.cfg, travis/test-conf/webchat.cfg
Add  build tests(they are free and can work with forks. So it will help to make sure that a PR code works):
- Test if we can build LalkaChat
- Test if we can launch LalkaChat, connect to streaming platforms, bootstrap models without crashing.
- Test if LalkaChat is properly started and available at http://localhost:8080/
https://travis-ci.org/JAremko/LalkaChat/builds/177396115
*We use pre-made config files to load all modules and connect to chats*
fixes #183  solves #184
=> add Travis and fix stuff

docker/run
=> LC-202 Small fixes to docker shell file

gui.py, http/czt/js/app.js, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/system.py, modules/messaging/webchat.py
=> LC-96 Change chat modules logic

modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py
=> LC-145 Highlight message by filter

modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/system.py, modules/messaging/levels.py
=> LC-195 Categorize system messages

http/czt/css/style.css, http/czt/settings.json, http/czt/settings_gui.json, modules/messaging/webchat.py
=> LC-191 Add more customization to default style

LICENSE, gui.py, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/module.py, modules/helper/parser.py, modules/helper/system.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-132 Pick License

http/czt/js/app.js
About #210
It's not an issue, cause we are remove (not escaping) potential vulnerability code.
=> LC-210 v0.3.5 Sanitize html

README.md
=> LC-133 Readme

modules/messaging/levels.py
=> LC224 - Unique them ids

modules/chat/sc2tv.py, translations/en/sc2tv.key, translations/ru/sc2tv.key
=> LC167 - Funstream to peka2

main.py, messaging.py, modules/helper/system.py, modules/messaging/webchat.py, setup.py
=> LC-221 - Move static/functions from main to different file P1

modules/helper/system.py, modules/messaging/levels.py, modules/messaging/webchat.py, setup.py
=> LC-233 Fix theme unique ids

modules/messaging/webchat.py
=> LC-235 Make cherrypy render all css files

gui.py, main.py, modules/helper/module.py, modules/messaging/levels.py, modules/messaging/test_module.py, modules/messaging/webchat.py, requires.txt, src/themes/default/assets/css/style.scss
=> LC-216 Rewrite GUI

src/themes/default/app/app.js
=> LC-246 #246 Make html tags great again [2]

gui.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-215 Style settings do not update in gui after changing theme

src/themes/default/config/webpack.common.js, src/themes/default/config/webpack.production.js, src/themes/default/package.json
add jest tests
update webpack, optimize build
=> LC-238 0.3.6 Javascript test's

Jenkinsfile
=> LC-264 Docker Containers

Jenkinsfile, README.md, docker/dockerfiles/fedora/build-deps/Dockerfile, main.py, modules/helper/system.py, modules/messaging/webchat.py, src/jenkins/cfg/config.cfg, src/jenkins/cfg/messaging_modules.cfg, src/jenkins/prep_config.sh, src/jenkins/run_chat.sh
=> LC-274 Basic Docker testing functionality

Jenkinsfile, docker/dockerfiles/alpine/build-deps/Dockerfile, docker/dockerfiles/alpine/testing/Dockerfile, docker/dockerfiles/fedora/build-deps/Dockerfile, docker/dockerfiles/fedora/testing/Dockerfile, src/jenkins/get_chat_tests.py, src/jenkins/get_folder_tests.py, src/jenkins/lint_tests/css_test.sh, src/jenkins/lint_tests/helpers/css_test.py
=> LC-239 Jenkins CSS Tests

gui.py, modules/messaging/levels.py, modules/messaging/webchat.py
=> LC-286 Make sure cef runs without app cache

modules/helper/module.py
=> LC-263 Status sending fix

gui.py, main.py
=> LC-291 Log level should be specified in settings

modules/chat/goodgame.py
=> LC-241 Fix rendering of goodgame smiles

modules/chat/sc2tv.py
=> LC-261 sc2tv smiles fix

modules/messaging/webchat.py, src/themes/default/assets/css/style.scss, src/themes/default/assets/settings.json, src/themes/default/assets/settings_gui.json
=> LC-307 More settings for style

requires_linux.txt
=> LC-259 ws4py compatablity

modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py
=> LC-257 Chats will try to reconnect after small timeout

modules/helper/parser.py, modules/messaging/webchat.py
=> LC-244 YAML unicode to file

modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py
=> LC-323 Status window refresh fix

.gitignore, src/jenkins/root/main.spec
=> LC-303 Try to run compiled chat without tcl/tk folders

Jenkinsfile, gui.py, modules/chat/twitch.py
=> LC-196 Twitch.tv bits support

gui.py, main.py, modules/chat/twitch.py, modules/messaging/levels.py
=> LC-305 Fix levels

Jenkinsfile, modules/chat/twitch.py, src/themes/default/assets/index.html
=> LC-310 Twitch nicknames coloring

gui.py, main.py, modules/helper/module.py, modules/helper/parser.py
=> LC-311 Button can now trigger function

main.py
=> LC-341 Fix CPU usage

.gitignore, gui.py, main.py, messaging.py, modules/chat/goodgame.py, modules/helper/module.py, modules/helper/system.py, modules/messaging/levels.py, modules/messaging/webchat.py, translations/en/main.key, translations/en/twitch.key, translations/ru/main.key, translations/ru/twitch.key
=> LC-343 Prepare for 0.3.6 release

gui.py, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/module.py, modules/helper/parser.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/test_module.py, modules/messaging/webchat.py
=> LC-350 Rewrote module init logic

modules/messaging/c2b.py
=> LC-366 cloud2butt should only replace whole words

modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/module.py, modules/helper/system.py, modules/messaging/c2b.py, src/jenkins/cfg/chat_modules.cfg, src/jenkins/cfg/hitbox.cfg, src/jenkins/chat_tests/hitbox.sh, src/jenkins/run_chat.sh
=> LC-338 hitbox chat

Jenkinsfile, docker/dockerfiles/alpine/testing/Dockerfile, docker/dockerfiles/fedora/testing/Dockerfile, src/jenkins/tests_to_xml.py
=> LC-373 Convert python tests report to junit format

Jenkinsfile
=> LC-349 Fix docker jenkins

Jenkinsfile, messaging.py, modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/message.py, modules/helper/module.py, modules/helper/system.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-355 Message Refactor

modules/chat/twitch.py, modules/helper/message.py, modules/helper/module.py, src/themes/default/assets/index.html
=> LC-377 Twitch subscriptions

main.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/gui.py, modules/interface/controls.py, modules/interface/functions.py, modules/messaging/webchat.py
=> LC-335 Split GUI file

modules/chat/twitch.py, modules/helper/message.py, src/themes/default/assets/index.html
=> LC-370 fix twitch /me

modules/chat/goodgame.py
=> LC-385 Allow to use channelid instead of nickname

main.py, messaging.py, modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/gui.py, modules/helper/functions.py, modules/helper/module.py, modules/helper/parser.py, modules/helper/system.py, modules/interface/controls.py, modules/interface/functions.py, modules/interface/types.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py, translations/en/webchat.key
=> LC-393 Interface types change to Objects

modules/chat/twitch.py, modules/gui.py, modules/helper/message.py, src/jenkins/chat_tests/hitbox.sh, src/jenkins/run_chat.sh
=> LC-396 Remove display name from twitch

modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/message.py, modules/interface/types.py, modules/messaging/logger.py, modules/messaging/webchat.py
=> LC-395 Refactor platform format

modules/chat/twitch.py, modules/gui.py, modules/helper/system.py, modules/interface/frames.py, modules/interface/functions.py, modules/messaging/webchat.py
=> LC-337 OAuth for Twitch.TV

modules/gui.py, modules/interface/events.py, modules/messaging/webchat.py
=> LC-260 Fix Counters to be "thread-safe"

src/themes/default/assets/index.html
=> LC-405 Adapt html to new message format

Jenkinsfile
=> LC-407 Build Themes to blob

messaging.py, modules/gui.py, modules/helper/functions.py, modules/messaging/webchat.py
=> LC-418 Improve config parsing

Jenkinsfile, src/jenkins/publish_chat.sh
=> LC-420 Move publish stage to shellscript

src/jenkins/publish_chat.sh
=> LC-422 Workaround for themes

main.py
=> LC-414 Rotate main chat log

modules/gui.py, modules/interface/functions.py
=> LC-243 Gridbox updates if item changed inside

Jenkinsfile, main.py, messaging.py, modules/chat/goodgame.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/helper/functions.py, modules/helper/module.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/test_module.py, modules/messaging/webchat.py, src/jenkins/chat_tests/_bad/sc2tv.py
=> LC-344 Class PEP8

src/themes/default/app/app.js
=> LC-428 Bad path in websocket init

main.py, messaging.py, modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/gui.py, modules/helper/module.py
=> LC-390 Fix for window size if switched from non-browser start

main.py, messaging.py, modules/chat/beampro.py, modules/chat/goodgame.py, modules/chat/hitbox.py, modules/chat/sc2tv.py, modules/chat/twitch.py, modules/gui.py, modules/helper/module.py, modules/interface/types.py, modules/messaging/blacklist.py, modules/messaging/c2b.py, modules/messaging/df.py, modules/messaging/levels.py, modules/messaging/logger.py, modules/messaging/mentions.py, modules/messaging/webchat.py
=> LC-416 Move gui information to class

modules/helper/html_template.py, modules/messaging/webchat.py
=> LC-434 redirect boilerplate

modules/gui.py, modules/helper/system.py, modules/interface/frames.py
=> LC-409 Do not show counters when zero sources

modules/helper/message.py, modules/interface/frames.py, modules/messaging/webchat.py
=> LC-437 Add timestamp to message

modules/helper/message.py, modules/messaging/webchat.py
=> LC-439 Switch to unixtime

modules/messaging/webchat.py, requires_linux.txt, requires_windows.txt
=> LC-441 Sanitize message

src/themes/default/app/app.js, src/themes/default/assets/css/style.scss, src/themes/default/package.json
=> LC-353 Add twemoji
